version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-fraud
    ports:
      - "7474:7474"   # HTTP interface
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
