version: "3.9"

services:
  spark-master:
    image: apache/spark:3.4.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master"
    ports:
      - "7077:7077"      # Spark master
      - "8080:8080"      # Web UI
    volumes:
      - ./app:/app
    networks:
      - spark-network

  spark-worker-1:
    image: apache/spark:3.4.1
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077"
    depends_on:
      - spark-master
    volumes:
      - ./app:/app
    networks:
      - spark-network
    ports:
      - "8081:8081"

  spark-worker-2:
    image: apache/spark:3.4.1
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077"
    depends_on:
      - spark-master
    volumes:
      - ./app:/app
    networks:
      - spark-network
    ports:
      - "8082:8081"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spark-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

