version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/frontend
      - ./admin:/var/www/admin
    depends_on:
      - api
    networks:
      - appnet

  api:
    image: python:3.11-slim
    command: python3 /app/server.py
    volumes:
      - ./api:/app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
