version: '3.8'

services:
  citus-coordinator:
    image: citusdata/citus:12.1
    container_name: citus-coordinator
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: citus
    ports:
      - "5432:5432"
    networks:
      - citus-network

  citus-worker1:
    image: citusdata/citus:12.1
    container_name: citus-worker1
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: citus
    ports:
      - "5433:5432"
    networks:
      - citus-network

  citus-worker2:
    image: citusdata/citus:12.1
    container_name: citus-worker2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: citus
    ports:
      - "5434:5432"
    networks:
      - citus-network

networks:
  citus-network:
    driver: bridge
