apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqlinstances.mysql.my.domain
spec:
  group: mysql.my.domain
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                storage:
                  type: string
                username:
                  type: string
                password:
                  type: string
  scope: Namespaced
  names:
    plural: mysqlinstances
    singular: mysqlinstance
    kind: MySQLInstance
    shortNames:
    - mi
