version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper

  pinot-controller:
    image: apachepinot/pinot:latest
    container_name: pinot-controller
    command: StartController -zkAddress zookeeper:2181
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  pinot-broker:
    image: apachepinot/pinot:latest
    container_name: pinot-broker
    command: StartBroker -zkAddress zookeeper:2181
    ports:
      - "8099:8099"
    depends_on:
      pinot-controller:
        condition: service_healthy
    restart: on-failure

  pinot-server-1:
    image: apachepinot/pinot:latest
    container_name: pinot-server-1
    command: StartServer -zkAddress zookeeper:2181
    ports:
      - "8098:8098"
    depends_on:
      - pinot-controller

  pinot-server-2:
    image: apachepinot/pinot:latest
    container_name: pinot-server-2
    command: StartServer -zkAddress zookeeper:2181
    ports:
      - "8097:8097"
    depends_on:
      - pinot-controller
