version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: superset_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - superset-net

  superset:
    image: apache/superset:latest-dev
    depends_on:
      - postgres
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "secret"
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/superset_db
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - superset-net

volumes:
  postgres-data:
  superset_home:

networks:
  superset-net:
    driver: bridge
