version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870    # NameNode Web UI
      - 9000:9000    # HDFS API
      - 8020:8020    # Namenode IPC port (important)
    volumes:
      - ./hadoop_namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    ports:
      - 9864:9864    # DataNode Web UI
      - 50075:50075  # DataNode HTTP
    volumes:
      - ./hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: namenode:9870
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks:
      - hadoop-net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    ports:
      - 9865:9864    # DataNode Web UI for datanode2
      - 50076:50075  # DataNode HTTP
    volumes:
      - ./hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: namenode:9870
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge
