version: "3.8"

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - appnet

  backend1:
    image: python:3.11-slim
    environment:
      app_name: app_1
    volumes: [ "./backend:/app" ]
    command: python3 /app/server.py
    networks: [appnet]

  backend2:
    image: python:3.11-slim
    environment:
      app_name: app_2
    volumes: [ "./backend:/app" ]
    command: python3 /app/server.py
    networks: [appnet]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend1
      - backend2
    networks:
      - appnet

networks:
  appnet:
