version: "3.8"

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - appnet

  backend:
    image: python:3.11-slim
    command: python3 /app/server.py
    volumes:
      - ./backend:/app
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

networks:
  appnet:
