version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: trino
      POSTGRES_PASSWORD: trino
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    networks:
      - trino-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: trino
      MYSQL_PASSWORD: trino
    ports:
      - "3306:3306"
    networks:
      - trino-network

  coordinator:
    image: trinodb/trino:latest
    container_name: trino-coordinator
    volumes:
      - ./config/coordinator:/etc/trino
    ports:
      - "8080:8080"
    environment:
      - NODE_ID=coordinator
    networks:
      - trino-network

  worker1:
    image: trinodb/trino:latest
    container_name: trino-worker1
    depends_on:
      - coordinator
    volumes:
      - ./config/worker:/etc/trino
    environment:
      - NODE_ID=worker1
    networks:
      - trino-network

  worker2:
    image: trinodb/trino:latest
    container_name: trino-worker2
    depends_on:
      - coordinator
    volumes:
      - ./config/worker:/etc/trino
    environment:
      - NODE_ID=worker2
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge
