version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870    # NameNode Web UI
      - 9000:9000    # HDFS API
      - 8020:8020    # Namenode IPC port (important)
    volumes:
      - ./hadoop_namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net

  resourcemanager: # <--- NEW SERVICE ADDED
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088 
      - 8032:8032
      - 8030:8030
      - 8031:8031
    environment:
      SERVICE_PRECONDITION: namenode:9000
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks:
      - hadoop-net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    ports:
      - 9864:9864
      - 50075:50075
    volumes:
      - ./hadoop_datanode1:/hadoop/dfs/data
      - ./startup.sh:/startup.sh
    environment:
      SERVICE_PRECONDITION: namenode:9870
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - resourcemanager
    networks:
      - hadoop-net
    command: ["/startup.sh"] 

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    ports:
      - 9865:9864
      - 50076:50075
    volumes:
      - ./hadoop_datanode2:/hadoop/dfs/data
      - ./startup.sh:/startup.sh
    environment:
      SERVICE_PRECONDITION: namenode:9870
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - resourcemanager
    networks:
      - hadoop-net
    command: ["/startup.sh"] 

  hive-metastore-db:
    image: postgres:13
    container_name: hive-metastore-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hive
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
    volumes:
      - ./hive_metastore_db:/var/lib/postgresql/data
    networks:
      - hadoop-net

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    environment:
      SERVICE_PRECONDITION: hive-metastore-db:5432
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore-db:5432/hive"
      HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName: "org.postgresql.Driver"
      HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName: "hiveuser"
      HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword: "hivepassword"
      HIVE_CORE_CONF_hive_metastore_warehouse_dir: "hdfs://namenode:9000/user/hive/warehouse"
      HIVE_CORE_CONF_datanucleus_schema_autoCreateAll: "true"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      SERVICE: metastore
      HIVE_CONF_hive_execution_engine: tez # (Already there)
    ports:
      - "9083:9083"
    volumes:
      - ./hive_metastore_data:/opt/hive/data
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
    depends_on:
      - hive-metastore-db
      - namenode
      - resourcemanager # <--- ADDED
    networks:
      - hadoop-net
    command: ["/opt/hive/bin/hive", "--service", "metastore"]

  hiveserver:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hiveserver
    restart: always
    environment:
      SERVICE_PRECONDITION: hive-metastore:9083
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore-db:5432/hive"
      HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName: "org.postgresql.Driver"
      HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName: "hiveuser"
      HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword: "hivepassword"
      HIVE_CORE_CONF_hive_metastore_warehouse_dir: "hdfs://namenode:9000/user/hive/warehouse"
      HIVE_CORE_CONF_hive_server2_thrift_port: "10000"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
      MAPRED_CONF_mapreduce_framework_name: yarn
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./hive_server_data:/opt/hive/data
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
    depends_on:
      - hive-metastore
      - namenode
      - resourcemanager # <--- ADDED
    networks:
      - hadoop-net
    env_file:
      - ./hadoop.env

networks:
  hadoop-net:
    driver: bridge
