version: '3.8'

services:
  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra-network
    ports:
      - "9042:9042"  # CQL port
      - "9160:9160"  # Thrift port
      - "8000:7000"  # Inter-node communication
      - "8001:7001"  # SSL inter-node communication
      - "7199:7199"  # JMX port
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra1-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra-network
    ports:
      - "9043:9042"
      - "9161:9160"
      - "8002:7000"
      - "8003:7001"
      - "7200:7199"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra2-data:/var/lib/cassandra
    depends_on:
      cassandra1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  cassandra3:
    image: cassandra:4.1
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra-network
    ports:
      - "9044:9042"
      - "9162:9160"
      - "8004:7000"
      - "8005:7001"
      - "7201:7199"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra3-data:/var/lib/cassandra
    depends_on:
      cassandra2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  cassandra4:
    image: cassandra:4.1
    container_name: cassandra4
    hostname: cassandra4
    networks:
      - cassandra-network
    ports:
      - "9045:9042"
      - "9163:9160"
      - "8006:7000"
      - "8007:7001"
      - "7202:7199"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack4
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra4-data:/var/lib/cassandra
    depends_on:
      cassandra3:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  cassandra-network:
    driver: bridge

volumes:
  cassandra1-data:
  cassandra2-data:
  cassandra3-data:
  cassandra4-data:
