# I don't know why this exists. Committing just in case
version: '3.8'
services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: ["--replSet", "myReplicaSet", "--bind_ip", "0.0.0.0"]
    ports:
      - "27017:27017"
    networks:
      - mongo-net

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: ["--replSet", "myReplicaSet", "--bind_ip", "0.0.0.0"]
    ports:
      - "27018:27017"
    networks:
      - mongo-net

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: ["--replSet", "myReplicaSet", "--bind_ip", "0.0.0.0"]
    ports:
      - "27019:27017"
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge

