version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=demo-org
      - DOCKER_INFLUXDB_INIT_BUCKET=demo-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=demo-token

volumes:
  influxdb-data:
